services:

  haproxy:
    network_mode: host
    build:
      context: ./
      dockerfile: haproxy/Dockerfile
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
      - ./haproxy/errors/:/etc/haproxy/errors/
      - ./haproxy/map/:/etc/haproxy/map/
      - ./haproxy/template/:/etc/haproxy/template/
      - ./src/lua/scripts/:/etc/haproxy/scripts/
      - ./src/lua/libs/:/etc/haproxy/libs/
      - ./src/js/:/etc/haproxy/js/
      - ./src/locales/:/etc/haproxy/locales/
      - ../../Documents/dataplaneapi/build/dataplaneapi:/usr/local/bin/dataplaneapi
    environment:
      # test keys
      - HCAPTCHA_SITEKEY=20000000-ffff-ffff-ffff-000000000002
      - HCAPTCHA_SECRET=0x0000000000000000000000000000000000000000
      - HAPROXY_MAXCONN=5000
      - VERIFY_BACKEND_SSL=1
      - VERIFY_BACKEND_SSL_VERIFYNONE=1
      - CAPTCHA_COOKIE_SECRET=changeme
      - POW_COOKIE_SECRET=changeme
      - HMAC_COOKIE_SECRET=changeme
      - RAY_ID=docker
      - CHALLENGE_EXPIRY=43200
      - BACKEND_NAME=servers
      - SERVER_PREFIX=websrv
      - CHALLENGE_INCLUDES_IP=true
      - ARGON_TIME=2
      - ARGON_KB=512
      - POW_DIFFICULTY=20
      - POW_TYPE=argon2
      - TOR_CONTROL_PORT_PASSWORD=changeme
      - USE_INTER_FONT=1
      # - USE_POSTHOG=1

  nginx:
    ports:
      - 1081:80
    image: "nginx:latest"
    volumes:
      - ./nginx/html:/usr/share/nginx/html

  # for testing with VERIFY_BACKEND_SSL=1  
  nginx-tls:
    image: "nginx:latest"
    ports:
      - 1082:443
    volumes:
      - ./nginx/html2:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/certs
