server {
    listen 80;
    listen 8080;
    listen 8880;
    listen 2052;
    listen 2082;
    listen 2086;
    listen 2095;

    server_name localhost;

    return 301 https://$host$request_uri;  # Redirect HTTP to HTTPS
}

server {
    listen 443 ssl;
    listen 2053 ssl;
    listen 2083 ssl;
    listen 2087 ssl;
    listen 2096 ssl;
    listen 8443 ssl;
    listen 8888 ssl;

    server_name localhost;

    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;

    location / {
        root /usr/share/nginx/html;  # Change this to your document root
        index index.html index.htm;
        expires 60s;
    }
}

